package com.cryptomcgrath.pyrexia.db

import com.cryptomcgrath.pyrexia.model.PyDevice

fun List<Device>.toPyDeviceList(): List<PyDevice> {
    return this.map {
        it.toPyDevice()
    }
}

private fun Device.toPyDevice(): PyDevice {
    return PyDevice(
        uid = this.uid,
        name = this.name,
        baseUrl = this.baseUrl,
        email = this.email,
        password = this.password,
        token = this.token
    )
}

fun PyDevice.toDevice(): Device {
    return Device(
        uid = this.uid, // autogenerated on insert
        name = this.name,
        baseUrl = this.baseUrl,
        email = this.email,
        password = this.password,
        token = this.token
    )
}